language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 15
notifications:
  email: false
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
